
// This file has been generated by the GUI designer. Do not modify.
namespace Glippy.Upload
{
	internal partial class UploadWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label labelType;
		private global::Gtk.RadioButton radiobuttonText;
		private global::Gtk.RadioButton radiobuttonImage;
		private global::Gtk.VBox vboxTextLabels;
		private global::Gtk.Label labelName;
		private global::Gtk.Label labelExpirationDate;
		private global::Gtk.VBox vboxTextEntries;
		private global::Gtk.Entry name;
		private global::Gtk.ComboBox expirationDate;
		private global::Gtk.VBox vboxTextLabels1;
		private global::Gtk.Label labelPrivacy;
		private global::Gtk.VBox vboxTextEntries1;
		private global::Gtk.ComboBox privacy;
		private global::Gtk.CheckButton useAccount;
		private global::Gtk.Notebook clipType;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textClip;
		private global::Gtk.Label label4;
		private global::Gtk.Image imageClip;
		private global::Gtk.Label label5;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ProgressBar progressbarUpload;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Button buttonUpload;
		private global::Gtk.Button buttonCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Glippy.Upload.UploadWindow
			this.Name = "Glippy.Upload.UploadWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Upload clipboard content");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(9));
			// Container child Glippy.Upload.UploadWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(12));
			// Container child vbox7.Gtk.Box+BoxChild
			this.labelType = new global::Gtk.Label ();
			this.labelType.Name = "labelType";
			this.labelType.Xalign = 0F;
			this.labelType.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Type:</b>");
			this.labelType.UseMarkup = true;
			this.labelType.Justify = ((global::Gtk.Justification)(2));
			this.vbox7.Add (this.labelType);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.labelType]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.radiobuttonText = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("_Text"));
			this.radiobuttonText.CanFocus = true;
			this.radiobuttonText.Name = "radiobuttonText";
			this.radiobuttonText.DrawIndicator = true;
			this.radiobuttonText.UseUnderline = true;
			this.radiobuttonText.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox7.Add (this.radiobuttonText);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobuttonText]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.radiobuttonImage = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("_Image"));
			this.radiobuttonImage.CanFocus = true;
			this.radiobuttonImage.Name = "radiobuttonImage";
			this.radiobuttonImage.DrawIndicator = true;
			this.radiobuttonImage.UseUnderline = true;
			this.radiobuttonImage.Group = this.radiobuttonText.Group;
			this.vbox7.Add (this.radiobuttonImage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobuttonImage]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add (this.vbox7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox7]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxTextLabels = new global::Gtk.VBox ();
			this.vboxTextLabels.Name = "vboxTextLabels";
			this.vboxTextLabels.Spacing = 6;
			this.vboxTextLabels.BorderWidth = ((uint)(6));
			// Container child vboxTextLabels.Gtk.Box+BoxChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.Name = "labelName";
			this.labelName.Xalign = 1F;
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("_Name:");
			this.labelName.UseUnderline = true;
			this.vboxTextLabels.Add (this.labelName);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxTextLabels [this.labelName]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(5));
			// Container child vboxTextLabels.Gtk.Box+BoxChild
			this.labelExpirationDate = new global::Gtk.Label ();
			this.labelExpirationDate.Name = "labelExpirationDate";
			this.labelExpirationDate.LabelProp = global::Mono.Unix.Catalog.GetString ("E_xpiration date:");
			this.labelExpirationDate.UseUnderline = true;
			this.vboxTextLabels.Add (this.labelExpirationDate);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxTextLabels [this.labelExpirationDate]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(5));
			this.hbox1.Add (this.vboxTextLabels);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxTextLabels]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxTextEntries = new global::Gtk.VBox ();
			this.vboxTextEntries.Name = "vboxTextEntries";
			this.vboxTextEntries.Spacing = 6;
			this.vboxTextEntries.BorderWidth = ((uint)(6));
			// Container child vboxTextEntries.Gtk.Box+BoxChild
			this.name = new global::Gtk.Entry ();
			this.name.CanFocus = true;
			this.name.Name = "name";
			this.name.IsEditable = true;
			this.name.InvisibleChar = '•';
			this.vboxTextEntries.Add (this.name);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxTextEntries [this.name]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vboxTextEntries.Gtk.Box+BoxChild
			this.expirationDate = global::Gtk.ComboBox.NewText ();
			this.expirationDate.AppendText (global::Mono.Unix.Catalog.GetString ("Never"));
			this.expirationDate.AppendText (global::Mono.Unix.Catalog.GetString ("1 month"));
			this.expirationDate.AppendText (global::Mono.Unix.Catalog.GetString ("1 day"));
			this.expirationDate.AppendText (global::Mono.Unix.Catalog.GetString ("1 hour"));
			this.expirationDate.AppendText (global::Mono.Unix.Catalog.GetString ("10 minutes"));
			this.expirationDate.Name = "expirationDate";
			this.expirationDate.Active = 0;
			this.vboxTextEntries.Add (this.expirationDate);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxTextEntries [this.expirationDate]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox1.Add (this.vboxTextEntries);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxTextEntries]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxTextLabels1 = new global::Gtk.VBox ();
			this.vboxTextLabels1.Name = "vboxTextLabels1";
			this.vboxTextLabels1.Spacing = 6;
			this.vboxTextLabels1.BorderWidth = ((uint)(6));
			// Container child vboxTextLabels1.Gtk.Box+BoxChild
			this.labelPrivacy = new global::Gtk.Label ();
			this.labelPrivacy.Name = "labelPrivacy";
			this.labelPrivacy.LabelProp = global::Mono.Unix.Catalog.GetString ("_Privacy:");
			this.labelPrivacy.UseUnderline = true;
			this.vboxTextLabels1.Add (this.labelPrivacy);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxTextLabels1 [this.labelPrivacy]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(5));
			this.hbox1.Add (this.vboxTextLabels1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxTextLabels1]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxTextEntries1 = new global::Gtk.VBox ();
			this.vboxTextEntries1.Name = "vboxTextEntries1";
			this.vboxTextEntries1.Spacing = 6;
			this.vboxTextEntries1.BorderWidth = ((uint)(6));
			// Container child vboxTextEntries1.Gtk.Box+BoxChild
			this.privacy = global::Gtk.ComboBox.NewText ();
			this.privacy.AppendText (global::Mono.Unix.Catalog.GetString ("Public"));
			this.privacy.AppendText (global::Mono.Unix.Catalog.GetString ("Unlisted"));
			this.privacy.Name = "privacy";
			this.privacy.Active = 1;
			this.vboxTextEntries1.Add (this.privacy);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxTextEntries1 [this.privacy]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxTextEntries1.Gtk.Box+BoxChild
			this.useAccount = new global::Gtk.CheckButton ();
			this.useAccount.Sensitive = false;
			this.useAccount.CanFocus = true;
			this.useAccount.Name = "useAccount";
			this.useAccount.Label = global::Mono.Unix.Catalog.GetString ("Use _account");
			this.useAccount.DrawIndicator = true;
			this.useAccount.UseUnderline = true;
			this.vboxTextEntries1.Add (this.useAccount);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxTextEntries1 [this.useAccount]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox1.Add (this.vboxTextEntries1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxTextEntries1]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.clipType = new global::Gtk.Notebook ();
			this.clipType.CanFocus = true;
			this.clipType.Name = "clipType";
			this.clipType.CurrentPage = 1;
			this.clipType.ShowBorder = false;
			this.clipType.ShowTabs = false;
			// Container child clipType.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textClip = new global::Gtk.TextView ();
			this.textClip.CanFocus = true;
			this.textClip.Name = "textClip";
			this.GtkScrolledWindow.Add (this.textClip);
			this.clipType.Add (this.GtkScrolledWindow);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.clipType.SetTabLabel (this.GtkScrolledWindow, this.label4);
			this.label4.ShowAll ();
			// Container child clipType.Gtk.Notebook+NotebookChild
			this.imageClip = new global::Gtk.Image ();
			this.imageClip.Name = "imageClip";
			this.clipType.Add (this.imageClip);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.clipType [this.imageClip]));
			w19.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.clipType.SetTabLabel (this.imageClip, this.label5);
			this.label5.ShowAll ();
			this.vbox1.Add (this.clipType);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.clipType]));
			w20.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.progressbarUpload = new global::Gtk.ProgressBar ();
			this.progressbarUpload.Name = "progressbarUpload";
			this.progressbarUpload.Text = "";
			this.hbox2.Add (this.progressbarUpload);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.progressbarUpload]));
			w21.Position = 0;
			w21.Padding = ((uint)(2));
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 26;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.alignment1.Add (this.fixed1);
			this.hbox3.Add (this.alignment1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
			w23.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonUpload = new global::Gtk.Button ();
			this.buttonUpload.WidthRequest = 60;
			this.buttonUpload.HeightRequest = 28;
			this.buttonUpload.CanDefault = true;
			this.buttonUpload.CanFocus = true;
			this.buttonUpload.Name = "buttonUpload";
			this.buttonUpload.UseUnderline = true;
			this.buttonUpload.Label = global::Mono.Unix.Catalog.GetString ("_Upload");
			this.hbox3.Add (this.buttonUpload);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonUpload]));
			w24.PackType = ((global::Gtk.PackType)(1));
			w24.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.WidthRequest = 60;
			this.buttonCancel.HeightRequest = 28;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("_Cancel");
			this.hbox3.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonCancel]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 2;
			this.hbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
			w26.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 568;
			this.DefaultHeight = 341;
			this.labelName.MnemonicWidget = this.name;
			this.labelExpirationDate.MnemonicWidget = this.expirationDate;
			this.labelPrivacy.MnemonicWidget = this.privacy;
			this.Show ();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.radiobuttonText.Toggled += new global::System.EventHandler (this.OnRadiobuttonTextToggled);
			this.radiobuttonImage.Toggled += new global::System.EventHandler (this.OnRadiobuttonImageToggled);
			this.useAccount.Toggled += new global::System.EventHandler (this.OnUseAccountToggled);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonUpload.Clicked += new global::System.EventHandler (this.OnButtonUploadClicked);
		}
	}
}
