
// This file has been generated by the GUI designer. Do not modify.
namespace Glippy.Screenshot
{
	internal partial class ColorWindow
	{
		private global::Gtk.VBox vbox14;
		private global::Gtk.HBox hbox9;
		private global::Gtk.VBox vbox24;
		private global::Gtk.HBox hbox15;
		private global::Gtk.HBox hbox16;
		private global::Gtk.VBox vbox29;
		private global::Gtk.Label label22;
		private global::Gtk.Label label23;
		private global::Gtk.Label label24;
		private global::Gtk.VBox vbox30;
		private global::Gtk.Label red;
		private global::Gtk.Label green;
		private global::Gtk.Label blue;
		private global::Gtk.HBox hbox14;
		private global::Gtk.VBox vbox25;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.VBox vbox27;
		private global::Gtk.Label hue;
		private global::Gtk.Label saturation;
		private global::Gtk.Label value;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Label label25;
		private global::Gtk.Label hex;
		private global::Gtk.DrawingArea color;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Button buttonClose;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Glippy.Screenshot.ColorWindow
			this.Name = "Glippy.Screenshot.ColorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Picked color");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(9));
			// Container child Glippy.Screenshot.ColorWindow.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 12;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox ();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 14;
			this.hbox15.BorderWidth = ((uint)(3));
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			this.hbox16.BorderWidth = ((uint)(3));
			// Container child hbox16.Gtk.Box+BoxChild
			this.vbox29 = new global::Gtk.VBox ();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 1F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Red:");
			this.vbox29.Add (this.label22);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox29 [this.label22]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 1F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Green:");
			this.vbox29.Add (this.label23);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox29 [this.label23]));
			w2.Position = 1;
			w2.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xalign = 1F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Blue:");
			this.vbox29.Add (this.label24);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox29 [this.label24]));
			w3.Position = 2;
			w3.Fill = false;
			this.hbox16.Add (this.vbox29);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.vbox29]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.vbox30 = new global::Gtk.VBox ();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			// Container child vbox30.Gtk.Box+BoxChild
			this.red = new global::Gtk.Label ();
			this.red.Name = "red";
			this.red.Selectable = true;
			this.vbox30.Add (this.red);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox30 [this.red]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.green = new global::Gtk.Label ();
			this.green.Name = "green";
			this.green.Selectable = true;
			this.vbox30.Add (this.green);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox30 [this.green]));
			w6.Position = 1;
			w6.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.blue = new global::Gtk.Label ();
			this.blue.Name = "blue";
			this.blue.Xalign = 0F;
			this.blue.Selectable = true;
			this.vbox30.Add (this.blue);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox30 [this.blue]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox16.Add (this.vbox30);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.vbox30]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox15.Add (this.hbox16);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.hbox16]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			this.hbox14.BorderWidth = ((uint)(3));
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox25 = new global::Gtk.VBox ();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Hue:");
			this.vbox25.Add (this.label10);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.label10]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Saturation:");
			this.vbox25.Add (this.label11);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.label11]));
			w11.Position = 1;
			w11.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Value:");
			this.vbox25.Add (this.label12);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.label12]));
			w12.Position = 2;
			w12.Fill = false;
			this.hbox14.Add (this.vbox25);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vbox25]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox27 = new global::Gtk.VBox ();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.hue = new global::Gtk.Label ();
			this.hue.Name = "hue";
			this.hue.Selectable = true;
			this.vbox27.Add (this.hue);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox27 [this.hue]));
			w14.Position = 0;
			w14.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.saturation = new global::Gtk.Label ();
			this.saturation.Name = "saturation";
			this.saturation.Selectable = true;
			this.vbox27.Add (this.saturation);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox27 [this.saturation]));
			w15.Position = 1;
			w15.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.value = new global::Gtk.Label ();
			this.value.Name = "value";
			this.value.Selectable = true;
			this.vbox27.Add (this.value);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox27 [this.value]));
			w16.Position = 2;
			w16.Fill = false;
			this.hbox14.Add (this.vbox27);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.vbox27]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox15.Add (this.hbox14);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.hbox14]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox24.Add (this.hbox15);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.hbox15]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			this.hbox17.BorderWidth = ((uint)(3));
			// Container child hbox17.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.Xalign = 1F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Hex:");
			this.hbox17.Add (this.label25);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label25]));
			w20.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.hex = new global::Gtk.Label ();
			this.hex.Name = "hex";
			this.hex.Xalign = 0F;
			this.hex.Selectable = true;
			this.hbox17.Add (this.hex);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.hex]));
			w21.Position = 1;
			this.vbox24.Add (this.hbox17);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.hbox17]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox9.Add (this.vbox24);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox24]));
			w23.Position = 0;
			w23.Expand = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.color = new global::Gtk.DrawingArea ();
			this.color.WidthRequest = 20;
			this.color.Name = "color";
			this.hbox9.Add (this.color);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.color]));
			w24.Position = 1;
			this.vbox14.Add (this.hbox9);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox9]));
			w25.Position = 0;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox1.Add (this.alignment6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment6]));
			w26.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 26;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.alignment4.Add (this.fixed1);
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment4]));
			w28.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.FocusOnClick = false;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString ("_Close");
			this.hbox1.Add (this.buttonClose);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonClose]));
			w29.PackType = ((global::Gtk.PackType)(1));
			w29.Position = 2;
			this.vbox14.Add (this.hbox1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox1]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.Add (this.vbox14);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 261;
			this.DefaultHeight = 169;
			this.Show ();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.buttonClose.Clicked += new global::System.EventHandler (this.OnButtonCloseClicked);
		}
	}
}
