
// This file has been generated by the GUI designer. Do not modify.
namespace Glippy.Screenshot
{
	internal partial class ImageWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox8;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label2;
		private global::Gtk.Label imageWidth;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Label label4;
		private global::Gtk.Label imageHeight;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label6;
		private global::Gtk.Label imageDate;
		private global::Gtk.Image preview;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonCopyToClipboard;
		private global::Gtk.Button buttonSaveToFile;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Button buttonClose;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Glippy.Screenshot.ImageWindow
			this.Name = "Glippy.Screenshot.ImageWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Image preview");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(9));
			// Container child Glippy.Screenshot.ImageWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 30;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Width:");
			this.hbox9.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.imageWidth = new global::Gtk.Label ();
			this.imageWidth.Name = "imageWidth";
			this.imageWidth.Xalign = 0F;
			this.hbox9.Add (this.imageWidth);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.imageWidth]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox8.Add (this.hbox9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox9]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Height:");
			this.hbox10.Add (this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.imageHeight = new global::Gtk.Label ();
			this.imageHeight.Name = "imageHeight";
			this.imageHeight.Xalign = 0F;
			this.hbox10.Add (this.imageHeight);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.imageHeight]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox8.Add (this.hbox10);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox10]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Date:");
			this.hbox11.Add (this.label6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label6]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.imageDate = new global::Gtk.Label ();
			this.imageDate.Name = "imageDate";
			this.imageDate.Xalign = 0F;
			this.hbox11.Add (this.imageDate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.imageDate]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox8.Add (this.hbox11);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox11]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.preview = new global::Gtk.Image ();
			this.preview.Name = "preview";
			this.vbox1.Add (this.preview);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.preview]));
			w11.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCopyToClipboard = new global::Gtk.Button ();
			this.buttonCopyToClipboard.CanFocus = true;
			this.buttonCopyToClipboard.Name = "buttonCopyToClipboard";
			this.buttonCopyToClipboard.UseUnderline = true;
			this.buttonCopyToClipboard.FocusOnClick = false;
			this.buttonCopyToClipboard.Label = global::Mono.Unix.Catalog.GetString ("C_opy to clipboard");
			this.hbox1.Add (this.buttonCopyToClipboard);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCopyToClipboard]));
			w12.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSaveToFile = new global::Gtk.Button ();
			this.buttonSaveToFile.CanFocus = true;
			this.buttonSaveToFile.Name = "buttonSaveToFile";
			this.buttonSaveToFile.UseUnderline = true;
			this.buttonSaveToFile.FocusOnClick = false;
			this.buttonSaveToFile.Label = global::Mono.Unix.Catalog.GetString ("_Save to file");
			this.hbox1.Add (this.buttonSaveToFile);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSaveToFile]));
			w13.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 26;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.alignment4.Add (this.fixed1);
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment4]));
			w15.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.HeightRequest = 26;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.alignment5.Add (this.fixed2);
			this.hbox1.Add (this.alignment5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment5]));
			w17.Position = 3;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.FocusOnClick = false;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString ("_Close");
			this.hbox1.Add (this.buttonClose);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonClose]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 4;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 509;
			this.DefaultHeight = 268;
			this.Show ();
			this.buttonCopyToClipboard.Clicked += new global::System.EventHandler (this.OnButtonCopyToClipboardClicked);
			this.buttonSaveToFile.Clicked += new global::System.EventHandler (this.OnButtonSaveToFileClicked);
			this.buttonClose.Clicked += new global::System.EventHandler (this.OnButtonCloseClicked);
		}
	}
}
