
// This file has been generated by the GUI designer. Do not modify.
namespace Glippy.Snippets
{
	internal partial class SnippetsPreferencesPage
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.CheckButton enable;
		private global::Gtk.CheckButton pasteOnSnippetSelection;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView snippets;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.Button buttonRemoveSnippet;
		private global::Gtk.Button buttonEditSnippet;
		private global::Gtk.Button buttonAddSnippet;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Glippy.Snippets.SnippetsPreferencesPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Glippy.Snippets.SnippetsPreferencesPage";
			// Container child Glippy.Snippets.SnippetsPreferencesPage.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 8;
			this.vbox7.BorderWidth = ((uint)(12));
			// Container child vbox7.Gtk.Box+BoxChild
			this.enable = new global::Gtk.CheckButton ();
			this.enable.CanFocus = true;
			this.enable.Name = "enable";
			this.enable.Label = global::Mono.Unix.Catalog.GetString ("Enable snippets");
			this.enable.DrawIndicator = true;
			this.enable.UseUnderline = true;
			this.enable.BorderWidth = ((uint)(5));
			this.vbox7.Add (this.enable);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.enable]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.pasteOnSnippetSelection = new global::Gtk.CheckButton ();
			this.pasteOnSnippetSelection.CanFocus = true;
			this.pasteOnSnippetSelection.Name = "pasteOnSnippetSelection";
			this.pasteOnSnippetSelection.Label = global::Mono.Unix.Catalog.GetString ("Paste content on snippet selection");
			this.pasteOnSnippetSelection.DrawIndicator = true;
			this.pasteOnSnippetSelection.UseUnderline = true;
			this.pasteOnSnippetSelection.BorderWidth = ((uint)(5));
			this.vbox7.Add (this.pasteOnSnippetSelection);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.pasteOnSnippetSelection]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(5));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.snippets = new global::Gtk.TreeView ();
			this.snippets.Sensitive = false;
			this.snippets.CanFocus = true;
			this.snippets.Name = "snippets";
			this.GtkScrolledWindow.Add (this.snippets);
			this.vbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow]));
			w4.Position = 2;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(6));
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox2.Add (this.alignment9);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment9]));
			w5.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonRemoveSnippet = new global::Gtk.Button ();
			this.buttonRemoveSnippet.Sensitive = false;
			this.buttonRemoveSnippet.CanFocus = true;
			this.buttonRemoveSnippet.Name = "buttonRemoveSnippet";
			this.buttonRemoveSnippet.UseUnderline = true;
			this.buttonRemoveSnippet.Label = global::Mono.Unix.Catalog.GetString ("_Remove");
			this.hbox2.Add (this.buttonRemoveSnippet);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonRemoveSnippet]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonEditSnippet = new global::Gtk.Button ();
			this.buttonEditSnippet.Sensitive = false;
			this.buttonEditSnippet.CanFocus = true;
			this.buttonEditSnippet.Name = "buttonEditSnippet";
			this.buttonEditSnippet.UseUnderline = true;
			this.buttonEditSnippet.Label = global::Mono.Unix.Catalog.GetString ("_Edit");
			this.hbox2.Add (this.buttonEditSnippet);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonEditSnippet]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonAddSnippet = new global::Gtk.Button ();
			this.buttonAddSnippet.Sensitive = false;
			this.buttonAddSnippet.CanFocus = true;
			this.buttonAddSnippet.Name = "buttonAddSnippet";
			this.buttonAddSnippet.UseUnderline = true;
			this.buttonAddSnippet.Label = global::Mono.Unix.Catalog.GetString ("_Add");
			this.hbox2.Add (this.buttonAddSnippet);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonAddSnippet]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 3;
			this.vbox7.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox2]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.enable.Toggled += new global::System.EventHandler (this.OnEnableToggled);
			this.pasteOnSnippetSelection.Toggled += new global::System.EventHandler (this.OnPasteOnSnippetSelectionToggled);
			this.buttonAddSnippet.Clicked += new global::System.EventHandler (this.OnButtonAddSnippetClicked);
			this.buttonEditSnippet.Clicked += new global::System.EventHandler (this.OnButtonEditSnippetClicked);
			this.buttonRemoveSnippet.Clicked += new global::System.EventHandler (this.OnButtonRemoveSnippetClicked);
		}
	}
}
