
// This file has been generated by the GUI designer. Do not modify.
namespace Glippy.UrlShortener
{
	internal partial class UrlShortenerPreferencesPage
	{
		private global::Gtk.VBox vbox9;
		private global::Gtk.VBox vbox14;
		private global::Gtk.HBox hbox10;
		private global::Gtk.VBox vbox16;
		private global::Gtk.Label labelShortener;
		private global::Gtk.VBox vbox17;
		private global::Gtk.ComboBox shortener;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox8;
		private global::Gtk.VBox vbox13;
		private global::Gtk.Label labelBitly1;
		private global::Gtk.HBox hbox7;
		private global::Gtk.VBox vbox12;
		private global::Gtk.Label labelBitlyUsername;
		private global::Gtk.Label labelBitlyApiKey;
		private global::Gtk.VBox vbox11;
		private global::Gtk.Entry bitlyUsername;
		private global::Gtk.Entry bitlyApiKey;
		private global::Gtk.Label labelBitly;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Glippy.UrlShortener.UrlShortenerPreferencesPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Glippy.UrlShortener.UrlShortenerPreferencesPage";
			// Container child Glippy.UrlShortener.UrlShortenerPreferencesPage.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 8;
			this.vbox9.BorderWidth = ((uint)(12));
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			this.hbox10.BorderWidth = ((uint)(3));
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.labelShortener = new global::Gtk.Label ();
			this.labelShortener.Name = "labelShortener";
			this.labelShortener.Xalign = 0F;
			this.labelShortener.LabelProp = global::Mono.Unix.Catalog.GetString ("_URL shortener:");
			this.labelShortener.UseUnderline = true;
			this.vbox16.Add (this.labelShortener);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.labelShortener]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(5));
			this.hbox10.Add (this.vbox16);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox16]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.shortener = global::Gtk.ComboBox.NewText ();
			this.shortener.AppendText (global::Mono.Unix.Catalog.GetString ("TinyURL.com"));
			this.shortener.AppendText (global::Mono.Unix.Catalog.GetString ("Bit.ly"));
			this.shortener.Name = "shortener";
			this.shortener.Active = 0;
			this.vbox17.Add (this.shortener);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.shortener]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox10.Add (this.vbox17);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox17]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox14.Add (this.hbox10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox10]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(5));
			this.vbox9.Add (this.vbox14);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox14]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.BorderWidth = ((uint)(3));
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			this.hbox8.BorderWidth = ((uint)(3));
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.labelBitly1 = new global::Gtk.Label ();
			this.labelBitly1.Name = "labelBitly1";
			this.labelBitly1.Xalign = 0F;
			this.labelBitly1.LabelProp = global::Mono.Unix.Catalog.GetString ("Bitly URL shortener requires your account details.\nYou can find your API key <a href=\"https://bitly.com/a/your_api_key\">here</a>.");
			this.labelBitly1.UseMarkup = true;
			this.labelBitly1.UseUnderline = true;
			this.labelBitly1.Wrap = true;
			this.vbox13.Add (this.labelBitly1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.labelBitly1]));
			w7.Position = 0;
			w7.Padding = ((uint)(5));
			this.hbox8.Add (this.vbox13);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox13]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox10.Add (this.hbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox8]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			this.hbox7.BorderWidth = ((uint)(3));
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.labelBitlyUsername = new global::Gtk.Label ();
			this.labelBitlyUsername.Name = "labelBitlyUsername";
			this.labelBitlyUsername.Xalign = 0F;
			this.labelBitlyUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("_Username");
			this.labelBitlyUsername.UseUnderline = true;
			this.vbox12.Add (this.labelBitlyUsername);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.labelBitlyUsername]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(5));
			// Container child vbox12.Gtk.Box+BoxChild
			this.labelBitlyApiKey = new global::Gtk.Label ();
			this.labelBitlyApiKey.Name = "labelBitlyApiKey";
			this.labelBitlyApiKey.Xalign = 0F;
			this.labelBitlyApiKey.LabelProp = global::Mono.Unix.Catalog.GetString ("_API key");
			this.labelBitlyApiKey.UseUnderline = true;
			this.vbox12.Add (this.labelBitlyApiKey);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.labelBitlyApiKey]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(5));
			this.hbox7.Add (this.vbox12);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox12]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.bitlyUsername = new global::Gtk.Entry ();
			this.bitlyUsername.CanFocus = true;
			this.bitlyUsername.Name = "bitlyUsername";
			this.bitlyUsername.IsEditable = true;
			this.bitlyUsername.InvisibleChar = '•';
			this.vbox11.Add (this.bitlyUsername);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.bitlyUsername]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.bitlyApiKey = new global::Gtk.Entry ();
			this.bitlyApiKey.CanFocus = true;
			this.bitlyApiKey.Name = "bitlyApiKey";
			this.bitlyApiKey.IsEditable = true;
			this.bitlyApiKey.Visibility = false;
			this.bitlyApiKey.InvisibleChar = '•';
			this.vbox11.Add (this.bitlyApiKey);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.bitlyApiKey]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox7.Add (this.vbox11);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox11]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			this.vbox10.Add (this.hbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox7]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			w16.Padding = ((uint)(5));
			this.GtkAlignment.Add (this.vbox10);
			this.frame2.Add (this.GtkAlignment);
			this.labelBitly = new global::Gtk.Label ();
			this.labelBitly.Name = "labelBitly";
			this.labelBitly.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Bit.ly account</b>");
			this.labelBitly.UseMarkup = true;
			this.frame2.LabelWidget = this.labelBitly;
			this.vbox9.Add (this.frame2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.frame2]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.labelShortener.MnemonicWidget = this.shortener;
			this.labelBitlyUsername.MnemonicWidget = this.bitlyUsername;
			this.labelBitlyApiKey.MnemonicWidget = this.bitlyApiKey;
			this.Hide ();
			this.shortener.Changed += new global::System.EventHandler (this.OnShortenerChanged);
			this.bitlyUsername.Changed += new global::System.EventHandler (this.OnBitlyUsernameChanged);
			this.bitlyApiKey.Changed += new global::System.EventHandler (this.OnBitlyApiKeyChanged);
		}
	}
}
